---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastiflow-es-pv
  labels:
    pv: elastiflow-es-pv
    app: elastiflow-es
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 198.18.100.9
    path: "/ocp-nfs/elastiflow-es"
    readOnly: false