---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastiflow-es-pvc
  labels:
    pv: elastiflow-es-pvc
    app: elastiflow-es
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: elastiflow-es-pv