---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastiflow-kibana
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: elastiflow-kibana
  template:
    metadata:
      labels:
        app: elastiflow-kibana
      name: elastiflow-kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:7.5.0
        ports:
        - name: kibana-http
          containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elastiflow-es:9200
        - name: KIBANA_DEFAULTAPPID
          value: dashboard/653cf1e0-2fd2-11e7-99ed-49759aed30f5
        - name: LOGGING_DEST
          value: stdout
        - name: LOGGING_QUIET
          value: "false"
        - name: SERVER_HOST
          value: 0.0.0.0
        - name: SERVER_MAXPAYLOADBYTES
          value: "4194304"
        - name: SERVER_PORT
          value: "5601"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastiflow-kibana
  name: elastiflow-kibana
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: kibana-http
  selector:
    app: elastiflow-kibana
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: elastiflow-kibana
  name: elastiflow-kibana
spec:
#  host: elastiflow-kibana-netflow.apps.ocp4poc.lab.shift.zone
  port:
    targetPort: 5601
  to:
    kind: Service
    name: elastiflow-kibana
    weight: 100
  wildcardPolicy: None